version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL="http://localhost:4000"

  backend:
    build: ./backend
    ports:
      - '4000:3000'
    volumes:
      - /app/node_modules
      - ./backend:/app
